[Service]
  Host = "edgex-device-grove"
  Port = 49991
  ConnectRetries = 3
  HealthCheck = ""
  StartupMsg = "device Grove PI started"
  ReadMaxLimit = 256
  Timeout = 5000

[Clients]
  [Clients.Data]
    Host = "edgex-core-data"
    Port = 48080

  [Clients.Metadata]
    Host = "edgex-core-metadata"
    Port = 48081

[Device]
  DataTransform = true
  Discovery = false
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = ""
  SendReadingsOnChanged = true

[Logging]
  RemoteURL = ""
  File = "-"

[[Schedules]]
  Name = "Schedule"
  Frequency = "PT2S"

[[ScheduleEvents]]
  Name = "SensorDist"
  Schedule = "Schedule"
  Path = "/api/v1/device/all/Get_SensorDist"

[[DeviceList]]
  Name = "GroveDevice"
  Profile = "Grove_Device"
  Description = "Grove Device to Read/Write sensors connected to GrovePI"
  Labels = [ "SensorDist", "LED"]
  [DeviceList.Addressable]
    Address = "GroveDevice"
    Port = 502
    Protocol = "OTHER"
