version: '3'

services:
  hivemq3:
    image: hivemq/hivemq3
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./hivemq.conf:/opt/hivemq-3.4.3/conf/config.xml
    container_name: hivemq3
    hostname: hivemq3
    networks:
      - edgex-network

  openvino_face_detect:
    image: byangintel/openvino_face_detect
    environment:
      - INPUT_STREAM=http://10.239.154.151:49990
    ports:
      - "49990:49990"
    container_name: openvino_face_detect
    hostname: openvino_face_detect
    networks:
      - edgex-network

networks:
  edgex-network:
    driver: "bridge"
...
