version: '3'

services:
  hivemq3:
    image: hivemq/hivemq3
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./hivemq.conf:/opt/hivemq-3.4.3/conf/config.xml
    container_name: hivemq3
    hostname: hivemq3
    networks:
      - edgex-network

  stream_mux:
    image: byangintel/stream_mux
    environment:
      - INPUT_STREAM=http://<Pi board ip>:49990
    ports:
      - "49999:49990"
    container_name: stream_mux
    hostname: stream_mux
    networks:
      - edgex-network

  openvino_face_detect-cpu:
    image: byangintel/openvino-face_detect-centos
    environment:
      - INPUT_STREAM=http://stream_mux:49990
    ports:
      - "49990:49990"
    container_name: openvino_face_detect-cpu
    hostname: openvino_face_detect-cpu
    networks:
      - edgex-network

  openvino_face_detect-gpu:
    image: byangintel/openvino-face_detect-centos
    environment:
      - INPUT_STREAM=http://stream_mux:49990
      - TARGET=GPU
    ports:
      - "49991:49990"
    volumes:
      - /dev:/dev
    privileged: true
    container_name: openvino_face_detect-gpu
    hostname: openvino_face_detect-gpu
    networks:
      - edgex-network

  openvino_face_detect-myriad:
    image: byangintel/openvino-face_detect-centos
    environment:
      - INPUT_STREAM=http://stream_mux:49990
      - TARGET=MYRIAD
    ports:
      - "49992:49990"
    volumes:
      - /dev:/dev
      - /sys:/sys
      - /proc/1/ns/net:/run/netns/host
    privileged: true
    container_name: openvino_face_detect-myriad
    hostname: openvino_face_detect-myriad
    networks:
      - edgex-network


networks:
  edgex-network:
    driver: "bridge"
...
